services:
    express-3000:
        build: server
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
        volumes:
            - ./data/data.txt:/app/data/data.txt
        networks:
            - backend
        environment:
            - PORT=3000
    express-4000:
        build: server
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
        volumes:
            - ./data/data.txt:/app/data/data.txt
        networks:
            - backend
        environment:
            - PORT=4000
    nginx:
        build: proxy
        ports:
            - '8080:80'
        networks:
            - backend
        depends_on:
            - express-3000
            - express-4000
networks:
    backend:
        driver: bridge
